@startuml Pintor 

class Dibujo{
    -lineas :list<string>
    -posicion : Vector
    -velocidad : Vector
    -estilo : Estilo
    + AgregarLinea()
}
class Vector{
    - posX
    - posY
}
class Archivo{
    -directorio : string
    +Leer(Dibujo)
    +LeerAnimacion(Animacion)
}
class Color 
class Estilo{
    -colorFondo
    -colorTexto
}
class Animacion {
    -fotogramas : list<Dibujo>
    -fotogramaActual : int 
}
class Lienzo{
     -dibujos : list<Dibujo>
     +Pintar()
     AgregarDibujo(Dibujo)
}

Dibujo *-- Vector 
Archivo o-- Dibujo 
Dibujo *-- Estilo 
Archivo o-- Animacion 
Lienzo o-- Dibujo 


@enduml